import type { Lead, Agent, RetentionCase, CallRecord, DailyStats, Affiliate, User } from "./types"

export const mockLeads: Lead[] = [
  {
    id: "1",
    name: "John Smith",
    phone: "(555) 123-4567",
    email: "john.smith@email.com",
    policyId: "POL-2024-001",
    carrier: "Blue Cross",
    status: "pending_lapse",
    fixType: "payment_issue",
    assignedAgent: "Sarah Johnson",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-18T14:30:00Z",
  },
  {
    id: "2",
    name: "Maria Garcia",
    phone: "(555) 234-5678",
    email: "maria.garcia@email.com",
    policyId: "POL-2024-002",
    carrier: "Aetna",
    status: "charged_back",
    fixType: "documentation",
    createdAt: "2024-01-16T09:00:00Z",
    updatedAt: "2024-01-16T09:00:00Z",
  },
  {
    id: "3",
    name: "Robert Johnson",
    phone: "(555) 345-6789",
    email: "robert.j@email.com",
    policyId: "POL-2024-003",
    carrier: "United Health",
    status: "issued_not_paid",
    fixType: "verification",
    assignedAgent: "Mike Chen",
    createdAt: "2024-01-17T11:00:00Z",
    updatedAt: "2024-01-19T16:00:00Z",
  },
  {
    id: "4",
    name: "Emily Davis",
    phone: "(555) 456-7890",
    email: "emily.d@email.com",
    policyId: "POL-2024-004",
    carrier: "Cigna",
    status: "pending_lapse",
    fixType: "payment_issue",
    createdAt: "2024-01-18T08:00:00Z",
    updatedAt: "2024-01-18T08:00:00Z",
  },
  {
    id: "5",
    name: "Michael Brown",
    phone: "(555) 567-8901",
    email: "m.brown@email.com",
    policyId: "POL-2024-005",
    carrier: "Humana",
    status: "in_progress",
    fixType: "customer_service",
    assignedAgent: "Sarah Johnson",
    createdAt: "2024-01-19T13:00:00Z",
    updatedAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "6",
    name: "Jennifer Wilson",
    phone: "(555) 678-9012",
    email: "j.wilson@email.com",
    policyId: "POL-2024-006",
    carrier: "Blue Cross",
    status: "new",
    fixType: "policy_change",
    createdAt: "2024-01-20T09:00:00Z",
    updatedAt: "2024-01-20T09:00:00Z",
  },
  {
    id: "7",
    name: "David Martinez",
    phone: "(555) 789-0123",
    email: "d.martinez@email.com",
    policyId: "POL-2024-007",
    carrier: "Aetna",
    status: "issued_paid",
    fixType: "payment_issue",
    assignedAgent: "Mike Chen",
    createdAt: "2024-01-14T10:00:00Z",
    updatedAt: "2024-01-20T15:00:00Z",
  },
  {
    id: "8",
    name: "Lisa Anderson",
    phone: "(555) 890-1234",
    email: "l.anderson@email.com",
    policyId: "POL-2024-008",
    carrier: "United Health",
    status: "charged_back",
    fixType: "documentation",
    createdAt: "2024-01-19T14:00:00Z",
    updatedAt: "2024-01-19T14:00:00Z",
  },
]

export const mockAgents: Agent[] = [
  {
    id: "agent-1",
    name: "Sarah Johnson",
    email: "sarah.j@company.com",
    role: "agent",
    activeLeads: 12,
    totalCalls: 145,
    successRate: 78,
  },
  {
    id: "agent-2",
    name: "Mike Chen",
    email: "mike.c@company.com",
    role: "agent",
    activeLeads: 8,
    totalCalls: 132,
    successRate: 82,
  },
  {
    id: "agent-3",
    name: "Amanda Torres",
    email: "amanda.t@company.com",
    role: "agent",
    activeLeads: 15,
    totalCalls: 98,
    successRate: 71,
  },
  {
    id: "agent-4",
    name: "James Wilson",
    email: "james.w@company.com",
    role: "agent",
    activeLeads: 6,
    totalCalls: 167,
    successRate: 85,
  },
]

export const mockRetentionCases: RetentionCase[] = [
  {
    id: "case-1",
    clientName: "John Smith",
    phone: "(555) 123-4567",
    leads: [mockLeads[0]],
    status: "in_progress",
    assignedAgent: "Sarah Johnson",
    priority: "high",
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "case-2",
    clientName: "Maria Garcia",
    phone: "(555) 234-5678",
    leads: [mockLeads[1]],
    status: "open",
    priority: "urgent",
    createdAt: "2024-01-16T09:00:00Z",
  },
]

export const mockCallRecords: CallRecord[] = [
  {
    id: "call-1",
    leadId: "1",
    agentId: "agent-1",
    duration: 245,
    outcome: "answered",
    notes: "Discussed payment options. Customer will call bank.",
    createdAt: "2024-01-20T10:30:00Z",
  },
  {
    id: "call-2",
    leadId: "3",
    agentId: "agent-2",
    duration: 120,
    outcome: "voicemail",
    notes: "Left voicemail requesting callback.",
    createdAt: "2024-01-20T11:15:00Z",
  },
]

export const mockDailyStats: DailyStats = {
  totalCalls: 47,
  totalTalkTime: 8520,
  fixAttempts: 32,
  successfulFixes: 18,
  pendingLeads: 24,
}

export const mockAffiliates: Affiliate[] = [
  {
    id: "aff-1",
    name: "InsurePro Partners",
    email: "contact@insurepro.com",
    totalLeads: 245,
    soldPolicies: 89,
    conversionRate: 36.3,
    totalCommission: 12450,
    pendingPayout: 2350,
    status: "active" as const,
  },
  {
    id: "aff-2",
    name: "Health First Agency",
    email: "leads@healthfirst.com",
    totalLeads: 189,
    soldPolicies: 72,
    conversionRate: 38.1,
    totalCommission: 9800,
    pendingPayout: 1200,
    status: "active" as const,
  },
  {
    id: "aff-3",
    name: "Premier Coverage",
    email: "info@premiercoverage.com",
    totalLeads: 156,
    soldPolicies: 45,
    conversionRate: 28.8,
    totalCommission: 6750,
    pendingPayout: 890,
    status: "active" as const,
  },
  {
    id: "aff-4",
    name: "QuickQuote Inc",
    email: "sales@quickquote.com",
    totalLeads: 98,
    soldPolicies: 31,
    conversionRate: 31.6,
    totalCommission: 4650,
    pendingPayout: 650,
    status: "pending" as const,
  },
]

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Alex Manager",
    email: "alex@company.com",
    role: "manager" as const,
    status: "active" as const,
    lastActive: "2024-01-20T15:30:00Z",
  },
  {
    id: "user-2",
    name: "Sarah Johnson",
    email: "sarah.j@company.com",
    role: "agent" as const,
    status: "active" as const,
    lastActive: "2024-01-20T16:00:00Z",
  },
  {
    id: "user-3",
    name: "Mike Chen",
    email: "mike.c@company.com",
    role: "agent" as const,
    status: "active" as const,
    lastActive: "2024-01-20T14:45:00Z",
  },
  {
    id: "user-4",
    name: "Amanda Torres",
    email: "amanda.t@company.com",
    role: "agent" as const,
    status: "active" as const,
    lastActive: "2024-01-20T12:00:00Z",
  },
  {
    id: "user-5",
    name: "James Wilson",
    email: "james.w@company.com",
    role: "agent" as const,
    status: "inactive" as const,
    lastActive: "2024-01-15T09:00:00Z",
  },
  {
    id: "user-6",
    name: "Admin User",
    email: "admin@company.com",
    role: "admin" as const,
    status: "active" as const,
    lastActive: "2024-01-20T16:30:00Z",
  },
]
